### ISSUE TITLE
OSError: Too many files open when doing DoS attacks.

### ISSUE THREAD

**Issue by Adil-MohammedK** [stfbk/mqttsa#7]
```
Performing Denial of Service...

Waiting for all publish acknowledgment (press ctrl+c once to skip):
30 seconds remaining
All acknowledgment received
Traceback (most recent call last):
  File "/home/IoTPi1/Wireshark/mqttsa/mqttsa.py", line 534, in <module>
  File "/home/IoTPi1/Wireshark/mqttsa/src/dos/broker_dos.py", line 454, in broker_dos
  File "/home/IoTPi1/Wireshark/mqttsa/src/dos/broker_dos.py", line 211, in flooding_dos
  File "/home/IoTPi1/Wireshark/mqttsa/src/dos/broker_dos.py", line 147, in init_client
  File "/home/IoTPi1/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1795, in loop_start
  File "/home/IoTPi1/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 277, in _socketpair_compat
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
```

Tried increasing OS limits by `uname -n` but didnt have any effects

**Comment by umorelli** [comment]
Thanks for the info and sorry for the late reply. I put a try-catch for the exception. Now it reaches the limit of the machine/os/broker.

On Ubuntu 22.04, I modified `/etc/security/limits.conf`, `/etc/systemd/user.conf` and `/etc/systemd/system.conf` with the same results: after the same number of clients, they keep disconnecting one another. On Windows 11 I have no restrictions (as long as CPU/RAM holds).
