### ISSUE TITLE
fpdf error while doing attacks?

### ISSUE THREAD

**Issue by mahbub2649** [stfbk/mqttsa#8]
Anyone knows why this is happening?

File "C:\ProgramData\miniconda3\lib\site-packages\fpdf\fpdf.py", line 408, in write_html
    html2pdf.feed(text)
  File "C:\ProgramData\miniconda3\lib\site-packages\fpdf\html.py", line 737, in feed
    super().feed(data)
  File "C:\ProgramData\miniconda3\lib\html\parser.py", line 110, in feed
    self.goahead(0)
  File "C:\ProgramData\miniconda3\lib\html\parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "C:\ProgramData\miniconda3\lib\html\parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "C:\ProgramData\miniconda3\lib\site-packages\fpdf\html.py", line 708, in handle_endtag
    self.table.render()
  File "C:\ProgramData\miniconda3\lib\site-packages\fpdf\table.py", line 171, in render
    raise FPDFException(
fpdf.errors.FPDFException: Inconsistent column count detected on row 6: it has 3 columns, whereas the top row has 4.

**Comment by frodes-bre** [comment]
Hello,
I also get these errors.

"Traceback (most recent call last):
  File "/home/pi/mqttsa/mqttsa.py", line 629, in <module>
    pdfw.output_pdf(write_results.outdated_broker)
  File "/home/pi/mqttsa/src/pdf_wrapper/pdf_wrapper.py", line 189, in output_pdf
    pdf.write_html(html.encode('utf-8').decode('latin-1'))
  File "/home/pi/mqttsa-venv/lib/python3.11/site-packages/fpdf/fpdf.py", line 408, in write_html
    html2pdf.feed(text)
  File "/home/pi/mqttsa-venv/lib/python3.11/site-packages/fpdf/html.py", line 737, in feed
    super().feed(data)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 413, in parse_endtag
    self.handle_endtag(elem)
  File "/home/pi/mqttsa-venv/lib/python3.11/site-packages/fpdf/html.py", line 708, in handle_endtag
    self.table.render()
  File "/home/pi/mqttsa-venv/lib/python3.11/site-packages/fpdf/table.py", line 171, in render
    raise FPDFException(
fpdf.errors.FPDFException: Inconsistent column count detected on row 6: it has 3 columns, whereas the top row has 4."

**Comment by slickpockets** [comment]
i had the same issue, ive created a PR here which solves the issue:
[link](https://github.com/stfbk/mqttsa/pull/9)

**Comment by umorelli** [comment]
> i had the same issue, ive created a PR here which solves the issue: [link](https://github.com/stfbk/mqttsa/pull/9)

Thanks for the suggestion :). I integrated the PR, but later removed the percentages to avoid the warnings in the prompt.
